### ISSUE TITLE
Cannot publish package System.IO.Abstractions.Extensions

### ISSUE THREAD

**Issue by gigi81** [System-IO-Abstractions/System.IO.Abstractions.Extensions#5]
**Describe the bug**
The package fails to publish to nuget

**To Reproduce**
Run the build in the main branch

**Expected behavior**
The package to be published during the build

**Additional context**
There is something wrong with the api key configuration or more likely seems like it is not possible to package to nuget.org packages with name starting with "System." anymore.
Should we rename the package or do you think you can have an exception granted?
I would rather rename if we want to add more extensions to support things like xml (as a new binary/package) as requested in other tickets, to keep them consistent. Happy to entertain suggestions for the naming...

Error in the build:
Pushing System.IO.Abstractions.Extensions.1.0.11.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 321ms
error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).

Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Error: Process completed with exit code 1.

**Comment by gigi81** [comment]
So IOAbstractionsGroup.Extensions
It is definitely more compact. It loses a bit of context but is also probably less redundant.
Group or team?

**Comment by fgreinacher** [comment]
@gigi81 I thought a bit about this and came to the following plan: I'll rename the parent organization to `TestableIO` because that better matches the overarching idea of the projects here. Going forward we should aim to have `TestableIO` as prefix for all packages, e.g. `TestableIO.System.IO.Abstractions` or in this case `TestableIO.System.IO.Abstractions.Extensions`. To keep it convenient for existing users I'd leave out the `TestableIO` prefix from the .NET namespace.

**Comment by gigi81** [comment]
ok sounds like a plan!
So I will keep everything the same and only set the PackageId in the csproj to 
TestableIO.System.IO.Abstractions.Extensions

**Comment by fgreinacher** [comment]
> ok sounds like a plan!
> So I will keep everything the same and only set the PackageId in the csproj to
> TestableIO.System.IO.Abstractions.Extensions

Yep, thanks!

**Comment by fgreinacher** [comment]
> @gigi81 I thought a bit about this and came to the following plan: I'll rename the parent organization to `TestableIO` because that better matches the overarching idea of the projects here. Going forward we should aim to have `TestableIO` as prefix for all packages, e.g. `TestableIO.System.IO.Abstractions` or in this case `TestableIO.System.IO.Abstractions.Extensions`. To keep it convenient for existing users I'd leave out the `TestableIO` prefix from the .NET namespace.
> 
> @inyutin-maxim Can you do the same for https://github.com/System-IO-Abstractions/System.IO.Abstractions.Analyzers?

@jpreese @tathamoddie Do you want to be involved in decisions like this?

**Comment by fgreinacher** [comment]
> > @gigi81 I thought a bit about this and came to the following plan: I'll rename the parent organization to `TestableIO` because that better matches the overarching idea of the projects here. Going forward we should aim to have `TestableIO` as prefix for all packages, e.g. `TestableIO.System.IO.Abstractions` or in this case `TestableIO.System.IO.Abstractions.Extensions`. To keep it convenient for existing users I'd leave out the `TestableIO` prefix from the .NET namespace.
> > @inyutin-maxim Can you do the same for https://github.com/System-IO-Abstractions/System.IO.Abstractions.Analyzers?
> 
> @jpreese @tathamoddie Before I start changing things: Do you want to be involved here?

I'll go forward with this. Ping me if something is unclear 😀
